# Generated by Django 2.0.3 on 2018-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupme_id', models.CharField(max_length=32, unique=True)),
                ('saucer_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
