# Generated by Django 2.2.5 on 2019-09-05 12:26

import os
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0002_historicalnickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='SaucerUser',
        ),
        migrations.AddField(
            model_name='historicalnickname',
            name='group_id',
            field=models.CharField(default=os.environ.get('GROUPME_GROUP_ID'), max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=64)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='groupme.Bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='groupme.UserInfo'),
        ),
    ]
