# Generated by Django 2.2.5 on 2019-09-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0002_historicalnickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SaucerUser',
        ),
    ]
