# Generated by Django 3.1.4 on 2020-12-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupme', '0002_optimize_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnickname',
            name='group_id',
            field=models.CharField(max_length=32),
        ),
    ]
