language: python
python: 3.7
dist: bionic

cache: pip

services:
  - docker

env:
  global:
    - DJANGO_ENV=test

before_install:
  - touch web.env
  - pip install pip --upgrade
  - pip install pipenv --upgrade

install:
  - pipenv install --deploy --dev
  - docker build --tag clarkperkins/saucerbot .

before_script:
  - docker-compose up -d

script:
  # Code linting
  - pipenv run pycodestyle saucerbot
  - pipenv run pylint saucerbot

  # Type checking
  - pipenv run mypy saucerbot

  # Unit tests
  - pipenv run pytest

  # Integration tests
  - docker-compose run web python manage.py migrate
  - docker-compose run web python manage.py loadbrews

after_success:
  - ./docker_push.sh
