language: python
python: 3.7
dist: bionic

cache: pip

env:
  - DJANGO_ENV=test

before_install:
  - pip install pipenv --upgrade

install:
  - pipenv install --dev

script:
  - pipenv run pycodestyle saucerbot
  - pipenv run pylint saucerbot
  - pipenv run mypy saucerbot
  - pipenv run pytest
