language: python
python:
  - "3.6"

sudo: false

cache: pip

before_install:
  - pip install pipenv --upgrade

install:
  - pipenv install --dev

# Eventually run tests here, but there are no tests yet :)
script:
  - pipenv run pycodestyle saucerbot
  - pipenv run mypy saucerbot
