language: python
python: 3.6
dist: xenial
sudo: required

cache: pip

env:
  - DJANGO_ENV=test

before_install:
  - pip install pipenv --upgrade

install:
  - pipenv install --dev

script:
  - pipenv run pycodestyle saucerbot
  - pipenv run pylint saucerbot
  - pipenv run mypy saucerbot
  - pipenv run pytest
