language: python
python:
  - "3.6"

sudo: false

cache: pip

before_install:
  - pip install pipenv --upgrade

install:
  - pipenv install --dev
  - pip install -e .

script:
  - pipenv run pycodestyle saucerbot
  - pipenv run mypy saucerbot
  - pipenv run pytest
