services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    image: clarkperkins/saucerbot
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - web.env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  dbdata:
