version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
  web:
    image: clarkperkins/saucerbot
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DJANGO_ENV: "${DJANGO_ENV}"
      BONSAI_URL: http://elasticsearch:9200
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      WEB_CONCURRENCY: 2
    depends_on:
      - elasticsearch
      - db
