version: '3.7'
services:
  elasticsearch:
    image: elastic/elasticsearch:7.2.0
    environment:
      discovery.type: single-node
      cluster.name: saucerbot
      node.name: saucerbot
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    image: clarkperkins/saucerbot
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DJANGO_ENV: "${DJANGO_ENV}"
      BONSAI_URL: http://elasticsearch:9200
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      WEB_CONCURRENCY: 2
    env_file:
      - web.env
    depends_on:
      - elasticsearch
      - db

volumes:
  esdata:
  dbdata:
