apiVersion: v1
kind: Service
metadata:
  name: {{ include "saucerbot.backendName" . }}
  labels:
    {{- include "saucerbot.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "saucerbot.backendSelectorLabels" . | nindent 4 }}
