apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saucerbot.discordBotName" . }}
  labels:
    {{- include "saucerbot.discordBotLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "saucerbot.discordBotSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.discordBot.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "saucerbot.discordBotSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saucerbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.discordBot.podSecurityContext | nindent 8 }}
      containers:
        - name: discord-bot
          securityContext:
            {{- toYaml .Values.discordBot.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - saucerbot
          args:
            - discord
            - run
          {{- with .Values.discordBot.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.discordBot.resources | nindent 12 }}
      {{- with .Values.discordBot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.discordBot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.discordBot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
