# Generated by Django 3.2.8 on 2021-10-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('nickname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64)),
                ('token_type', models.CharField(max_length=64)),
                ('refresh_token', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='historicalnickname',
            index=models.Index(fields=['guild_id', 'user_id'], name='discord_his_guild_i_b8502b_idx'),
        ),
        migrations.AddField(
            model_name='handler',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='discord.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord.guild'),
        ),
    ]
