# Generated by Django 3.2.8 on 2021-10-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDisplayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('display_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalNickname',
        ),
        migrations.AddIndex(
            model_name='historicaldisplayname',
            index=models.Index(fields=['guild_id', 'user_id'], name='discord_his_guild_i_5017c3_idx'),
        ),
    ]
