# Generated by Django 3.2.9 on 2021-11-10 04:12

from django.db import migrations, models
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Guild = apps.get_model("discord", "Guild")
    Channel = apps.get_model("discord", "Channel")
    db_alias = schema_editor.connection.alias

    for guild in Guild.objects.using(db_alias).all():
        guild.slug = slugify(guild.name)
        guild.save()

    for channel in Channel.objects.using(db_alias).all():
        channel.slug = slugify(channel.name)
        channel.save()


class Migration(migrations.Migration):
    dependencies = [
        ('discord', '0002_rename_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guild',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(set_slugs, lambda apps, schema_editor: None),
    ]
