# Generated by Django 3.2.9 on 2021-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_add_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='slug',
        ),
    ]
